-- INSERT PLATFORMS
INSERT INTO public.badge (id, "name") VALUES(nextval('badge_seq'), 'X-Box');
INSERT INTO public.badge (id, "name") VALUES(nextval('badge_seq'), 'Playstation');
INSERT INTO public.badge (id, "name") VALUES(nextval('badge_seq'), 'Nintendo');
INSERT INTO public.badge (id, "name") VALUES(nextval('badge_seq'), 'PC');
INSERT INTO public.badge (id, "name") VALUES(nextval('badge_seq'), 'Hardware');
INSERT INTO public.badge (id, "name") VALUES(nextval('badge_seq'), 'Portatéis');
INSERT INTO public.badge (id, "name") VALUES(nextval('badge_seq'), 'Smartphones');
INSERT INTO public.badge (id, "name") VALUES(nextval('badge_seq'), 'Cinema/Séries');
INSERT INTO public.badge (id, "name") VALUES(nextval('badge_seq'), 'Anime/HQ/Mangá');

-- INSERT USER FOR TEST
INSERT INTO public.users (id, "password", username, roles) VALUES(nextval('users_seq'), '$2a$10$uDl9KAxWThB2Lp2VOS4cVuPY4s5Uqf3lof4TFcrszgUmdKe0bkqzS', 'admin', '{ADMIN}');
INSERT INTO public.users (id, "password", username, roles) VALUES(nextval('users_seq'), '$2a$10$uDl9KAxWThB2Lp2VOS4cVuPY4s5Uqf3lof4TFcrszgUmdKe0bkqzS', 'user', '{USER}');
INSERT INTO public.users (id, "password", username, roles) VALUES(nextval('users_seq'), '$2a$10$uDl9KAxWThB2Lp2VOS4cVuPY4s5Uqf3lof4TFcrszgUmdKe0bkqzS', 'review', '{REVIEW}');

-- INSERT POST FOR TEST
INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title, urlmainimage, description) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<div class="section-text">
<div class="content-image mb-24"><figure style="width: 910px" class="wp-caption alignnone"><img width="910" height="568" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg" class="attachment-910x568 size-910x568" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-327x204.jpg 991w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg"><figcaption class="wp-caption-text">Créditos: Divulgação/Blizzard</figcaption></figure></div>
<p>Na última sexta-feira (16), a Blizzard fez a primeira transmissão de desenvolvedores de <strong>Diablo IV</strong> após o game chegar às lojas. Nela, o diretor Joe Shely afirmou que a empresa já está preparando um <strong>grande patch de atualização que deve trazer diversos buffs</strong> para as classes presentes no game.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-426aebdb-7381-46eb-b5cc-4994b71562d5" style="" data-google-query-id="CIKD2O-5y_8CFdCblQIdfxcDfw"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_0__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_0" name="google_ads_iframe_/21715141650,1071122/desktop_intext_0" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="4"></iframe></div></div></div>
<p>“<em>Nossa filosofia é priorizar a melhoria da escolha observando as coisas que não estão funcionando e as tornando melhores</em>”, <strong>afirmou Shely</strong>. “<em>Agora, não me senti assim nas duas últimas semanas, certo? E quando vim aqui hoje, estava pensando — não tenho uma camisa como essa —, mas eu pensei sobre comprar uma camisa e depois escrever ‘é hora dos buffs’. Eu não fiz isso, mas é hora dos buffs</em>”.</p>
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<lite-youtube videoid="3PO9OY7AIs4" playlabel="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" posterquality="sddefault" params="rel=0" title="Play: Video"></lite-youtube>
</div></figure>
<p>O diretor de Diablo IV não foi específico sobre o que deve mudar no RPG de ação, mas prometeu que <strong>builds que dependem da geração de recursos vão funcionar melho</strong>r. Ele também prometeu que as <a href="https://www.adrenaline.com.br/games/um-unico-chefe-de-diablo-iv-e-responsavel-por-2-de-suas-mortes/">Masmorras de Pesadelo do game</a> vão se tornar mais recompensadoras e trazer mais experiência do que passar pelos labirintos convencionais do jogo.</p>
<h2 id="h-nerfs-sao-necessarios-para-diablo-iv-prosperar">Nerfs são necessários para Diablo IV prosperar</h2>
<p>O gerente-geral da franquia Diablo, Rod Fergusson, também explicou que alguns nerfs que <a href="https://www.adrenaline.com.br/games/diablo-iv-blizzard-nerfou-areas-para-elas-darem-menos-experiencia/">não agradaram aos jogadores</a> são necessários para melhorar o estado geral do game. Segundo ele, as “fazendas de experiência” eliminadas em uma atualização recente <strong>estavam fazendo com que outras partes da aventura acabassem sendo ignoradas</strong>.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-ebedeb73-2363-4dbf-9898-da9b920b111d" style="" data-google-query-id="CNGJ95y_8CFQSGlQIdgeoNAA"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_1__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_1" name="google_ads_iframe_/21715141650,1071122/desktop_intext_1" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="3"></iframe></div></div></div>
<figure class="wp-block-image size-full"><img decoding="async" width="1000" height="563" src="https://uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" class="wp-image-393905" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=640&amp;height=360&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-640x360.jpg 640w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=768&amp;height=432&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-768x432.jpg 768w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=150&amp;height=84&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-150x84.jpg 150w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=1000&amp;height=563&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg 1000w" sizes="(max-width: 1000px) 100vw, 1000px"><figcaption class="wp-element-caption">Foto: Divulgação/Blizzard</figcaption></figure>
<p>Durante a transmissão, os membros da Blizzard também revelaram que as gemas e outros itens que podem ser inseridos em equipamentos <strong>vão deixar de ser colocados no inventário geral dos jogadores</strong>. Segundo Shely, a intenção é que elas passem as ser tratadas com outros materiais que podem ser usados para aprimorar os equipamentos usados.</p>
<p>A companhia também promete fazer diversas mudanças no endgame de Diablo IV, mas reconheceu que <strong>muitos jogadores ainda vão demorar a senti-las</strong>. Segundo a companhia, ainda é uma quantidade relativa pequena de pessoas que terminou a história principal, mas garantir que elas vão ter que o fazer após isso é uma de suas preocupações constantes.</p>
<div class="wp-block-seox-content-feeds">
<article class="feed feed-base feed-conteudo-destacado">
<div class="feed-head">
<small class="feed-head-text">Conteúdo Relacionado </small>
</div>
<div class="feed-bg">
<a href="https://www.adrenaline.com.br/games/campanha-devocao-a-lilith-incentiva-fas-de-diablo-iv-a-doarem-sangue-em-sao-paulo/" title="Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo">
<figure class="feed-image">
<img width="912" height="569" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg" class="attachment-912x569 size-912x569" alt="diablo-iv-doacao-sangue" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-327x204.jpg 992w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg"> <div class="feed-image-hover">
</div>
</figure>
<div class="feed-content">
<div class="line">
<p class="feed-hat hat">Convocação do inferno</p>
</div>
<p class="feed-title">Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo</p>
</div>
</a>
</div>
</article>
</div>
<p>Fonte: <a href="https://www.pcgamer.com/diablo-4-director-it-is-time-for-the-buffs/" target="_blank" rel="noreferrer noopener">PC Gamer</a></p><div style="width: 100%; height: 0; transition: height 1s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: none; line-height: normal; margin: 0 0 2px; padding: 0; color: #aaa; text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-d3807e7e-27b9-4029-a6e7-eefed2d9a517" style="display: block;"></div></div>
</div>', 'Diablo IV promete buffs para personagens, mudanças nas gemas e mais', 'https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&height=568&format=webp&quality=91&imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-pode-ganhar-novo-nivel-de-dificuldade-revela-dataminer-912x569.jpg', 'Diablo IV para PC, disponivel nas plataformas: Playstation, X-box, PC');

INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title, urlmainimage, description) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<div class="section-text">
<div class="content-image mb-24"><figure style="width: 910px" class="wp-caption alignnone"><img width="910" height="568" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg" class="attachment-910x568 size-910x568" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-327x204.jpg 991w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg"><figcaption class="wp-caption-text">Créditos: Divulgação/Blizzard</figcaption></figure></div>
<p>Na última sexta-feira (16), a Blizzard fez a primeira transmissão de desenvolvedores de <strong>Diablo IV</strong> após o game chegar às lojas. Nela, o diretor Joe Shely afirmou que a empresa já está preparando um <strong>grande patch de atualização que deve trazer diversos buffs</strong> para as classes presentes no game.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-426aebdb-7381-46eb-b5cc-4994b71562d5" style="" data-google-query-id="CIKD2O-5y_8CFdCblQIdfxcDfw"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_0__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_0" name="google_ads_iframe_/21715141650,1071122/desktop_intext_0" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="4"></iframe></div></div></div>
<p>“<em>Nossa filosofia é priorizar a melhoria da escolha observando as coisas que não estão funcionando e as tornando melhores</em>”, <strong>afirmou Shely</strong>. “<em>Agora, não me senti assim nas duas últimas semanas, certo? E quando vim aqui hoje, estava pensando — não tenho uma camisa como essa —, mas eu pensei sobre comprar uma camisa e depois escrever ‘é hora dos buffs’. Eu não fiz isso, mas é hora dos buffs</em>”.</p>
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<lite-youtube videoid="3PO9OY7AIs4" playlabel="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" posterquality="sddefault" params="rel=0" title="Play: Video"></lite-youtube>
</div></figure>
<p>O diretor de Diablo IV não foi específico sobre o que deve mudar no RPG de ação, mas prometeu que <strong>builds que dependem da geração de recursos vão funcionar melho</strong>r. Ele também prometeu que as <a href="https://www.adrenaline.com.br/games/um-unico-chefe-de-diablo-iv-e-responsavel-por-2-de-suas-mortes/">Masmorras de Pesadelo do game</a> vão se tornar mais recompensadoras e trazer mais experiência do que passar pelos labirintos convencionais do jogo.</p>
<h2 id="h-nerfs-sao-necessarios-para-diablo-iv-prosperar">Nerfs são necessários para Diablo IV prosperar</h2>
<p>O gerente-geral da franquia Diablo, Rod Fergusson, também explicou que alguns nerfs que <a href="https://www.adrenaline.com.br/games/diablo-iv-blizzard-nerfou-areas-para-elas-darem-menos-experiencia/">não agradaram aos jogadores</a> são necessários para melhorar o estado geral do game. Segundo ele, as “fazendas de experiência” eliminadas em uma atualização recente <strong>estavam fazendo com que outras partes da aventura acabassem sendo ignoradas</strong>.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-ebedeb73-2363-4dbf-9898-da9b920b111d" style="" data-google-query-id="CNGJ95y_8CFQSGlQIdgeoNAA"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_1__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_1" name="google_ads_iframe_/21715141650,1071122/desktop_intext_1" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="3"></iframe></div></div></div>
<figure class="wp-block-image size-full"><img decoding="async" width="1000" height="563" src="https://uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" class="wp-image-393905" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=640&amp;height=360&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-640x360.jpg 640w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=768&amp;height=432&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-768x432.jpg 768w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=150&amp;height=84&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-150x84.jpg 150w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=1000&amp;height=563&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg 1000w" sizes="(max-width: 1000px) 100vw, 1000px"><figcaption class="wp-element-caption">Foto: Divulgação/Blizzard</figcaption></figure>
<p>Durante a transmissão, os membros da Blizzard também revelaram que as gemas e outros itens que podem ser inseridos em equipamentos <strong>vão deixar de ser colocados no inventário geral dos jogadores</strong>. Segundo Shely, a intenção é que elas passem as ser tratadas com outros materiais que podem ser usados para aprimorar os equipamentos usados.</p>
<p>A companhia também promete fazer diversas mudanças no endgame de Diablo IV, mas reconheceu que <strong>muitos jogadores ainda vão demorar a senti-las</strong>. Segundo a companhia, ainda é uma quantidade relativa pequena de pessoas que terminou a história principal, mas garantir que elas vão ter que o fazer após isso é uma de suas preocupações constantes.</p>
<div class="wp-block-seox-content-feeds">
<article class="feed feed-base feed-conteudo-destacado">
<div class="feed-head">
<small class="feed-head-text">Conteúdo Relacionado </small>
</div>
<div class="feed-bg">
<a href="https://www.adrenaline.com.br/games/campanha-devocao-a-lilith-incentiva-fas-de-diablo-iv-a-doarem-sangue-em-sao-paulo/" title="Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo">
<figure class="feed-image">
<img width="912" height="569" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg" class="attachment-912x569 size-912x569" alt="diablo-iv-doacao-sangue" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-327x204.jpg 992w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg"> <div class="feed-image-hover">
</div>
</figure>
<div class="feed-content">
<div class="line">
<p class="feed-hat hat">Convocação do inferno</p>
</div>
<p class="feed-title">Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo</p>
</div>
</a>
</div>
</article>
</div>
<p>Fonte: <a href="https://www.pcgamer.com/diablo-4-director-it-is-time-for-the-buffs/" target="_blank" rel="noreferrer noopener">PC Gamer</a></p><div style="width: 100%; height: 0; transition: height 1s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: none; line-height: normal; margin: 0 0 2px; padding: 0; color: #aaa; text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-d3807e7e-27b9-4029-a6e7-eefed2d9a517" style="display: block;"></div></div>
</div>', 'Diablo IV promete buffs para personagens, mudanças nas gemas e mais', 'https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&height=568&format=webp&quality=91&imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-pode-ganhar-novo-nivel-de-dificuldade-revela-dataminer-912x569.jpg', 'Diablo IV para PC, disponivel nas plataformas: Playstation, X-box, PC');

INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title, urlmainimage, description) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<div class="section-text">
<div class="content-image mb-24"><figure style="width: 910px" class="wp-caption alignnone"><img width="910" height="568" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg" class="attachment-910x568 size-910x568" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-327x204.jpg 991w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg"><figcaption class="wp-caption-text">Créditos: Divulgação/Blizzard</figcaption></figure></div>
<p>Na última sexta-feira (16), a Blizzard fez a primeira transmissão de desenvolvedores de <strong>Diablo IV</strong> após o game chegar às lojas. Nela, o diretor Joe Shely afirmou que a empresa já está preparando um <strong>grande patch de atualização que deve trazer diversos buffs</strong> para as classes presentes no game.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-426aebdb-7381-46eb-b5cc-4994b71562d5" style="" data-google-query-id="CIKD2O-5y_8CFdCblQIdfxcDfw"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_0__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_0" name="google_ads_iframe_/21715141650,1071122/desktop_intext_0" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="4"></iframe></div></div></div>
<p>“<em>Nossa filosofia é priorizar a melhoria da escolha observando as coisas que não estão funcionando e as tornando melhores</em>”, <strong>afirmou Shely</strong>. “<em>Agora, não me senti assim nas duas últimas semanas, certo? E quando vim aqui hoje, estava pensando — não tenho uma camisa como essa —, mas eu pensei sobre comprar uma camisa e depois escrever ‘é hora dos buffs’. Eu não fiz isso, mas é hora dos buffs</em>”.</p>
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<lite-youtube videoid="3PO9OY7AIs4" playlabel="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" posterquality="sddefault" params="rel=0" title="Play: Video"></lite-youtube>
</div></figure>
<p>O diretor de Diablo IV não foi específico sobre o que deve mudar no RPG de ação, mas prometeu que <strong>builds que dependem da geração de recursos vão funcionar melho</strong>r. Ele também prometeu que as <a href="https://www.adrenaline.com.br/games/um-unico-chefe-de-diablo-iv-e-responsavel-por-2-de-suas-mortes/">Masmorras de Pesadelo do game</a> vão se tornar mais recompensadoras e trazer mais experiência do que passar pelos labirintos convencionais do jogo.</p>
<h2 id="h-nerfs-sao-necessarios-para-diablo-iv-prosperar">Nerfs são necessários para Diablo IV prosperar</h2>
<p>O gerente-geral da franquia Diablo, Rod Fergusson, também explicou que alguns nerfs que <a href="https://www.adrenaline.com.br/games/diablo-iv-blizzard-nerfou-areas-para-elas-darem-menos-experiencia/">não agradaram aos jogadores</a> são necessários para melhorar o estado geral do game. Segundo ele, as “fazendas de experiência” eliminadas em uma atualização recente <strong>estavam fazendo com que outras partes da aventura acabassem sendo ignoradas</strong>.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-ebedeb73-2363-4dbf-9898-da9b920b111d" style="" data-google-query-id="CNGJ95y_8CFQSGlQIdgeoNAA"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_1__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_1" name="google_ads_iframe_/21715141650,1071122/desktop_intext_1" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="3"></iframe></div></div></div>
<figure class="wp-block-image size-full"><img decoding="async" width="1000" height="563" src="https://uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" class="wp-image-393905" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=640&amp;height=360&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-640x360.jpg 640w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=768&amp;height=432&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-768x432.jpg 768w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=150&amp;height=84&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-150x84.jpg 150w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=1000&amp;height=563&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg 1000w" sizes="(max-width: 1000px) 100vw, 1000px"><figcaption class="wp-element-caption">Foto: Divulgação/Blizzard</figcaption></figure>
<p>Durante a transmissão, os membros da Blizzard também revelaram que as gemas e outros itens que podem ser inseridos em equipamentos <strong>vão deixar de ser colocados no inventário geral dos jogadores</strong>. Segundo Shely, a intenção é que elas passem as ser tratadas com outros materiais que podem ser usados para aprimorar os equipamentos usados.</p>
<p>A companhia também promete fazer diversas mudanças no endgame de Diablo IV, mas reconheceu que <strong>muitos jogadores ainda vão demorar a senti-las</strong>. Segundo a companhia, ainda é uma quantidade relativa pequena de pessoas que terminou a história principal, mas garantir que elas vão ter que o fazer após isso é uma de suas preocupações constantes.</p>
<div class="wp-block-seox-content-feeds">
<article class="feed feed-base feed-conteudo-destacado">
<div class="feed-head">
<small class="feed-head-text">Conteúdo Relacionado </small>
</div>
<div class="feed-bg">
<a href="https://www.adrenaline.com.br/games/campanha-devocao-a-lilith-incentiva-fas-de-diablo-iv-a-doarem-sangue-em-sao-paulo/" title="Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo">
<figure class="feed-image">
<img width="912" height="569" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg" class="attachment-912x569 size-912x569" alt="diablo-iv-doacao-sangue" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-327x204.jpg 992w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg"> <div class="feed-image-hover">
</div>
</figure>
<div class="feed-content">
<div class="line">
<p class="feed-hat hat">Convocação do inferno</p>
</div>
<p class="feed-title">Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo</p>
</div>
</a>
</div>
</article>
</div>
<p>Fonte: <a href="https://www.pcgamer.com/diablo-4-director-it-is-time-for-the-buffs/" target="_blank" rel="noreferrer noopener">PC Gamer</a></p><div style="width: 100%; height: 0; transition: height 1s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: none; line-height: normal; margin: 0 0 2px; padding: 0; color: #aaa; text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-d3807e7e-27b9-4029-a6e7-eefed2d9a517" style="display: block;"></div></div>
</div>', 'Diablo IV promete buffs para personagens, mudanças nas gemas e mais', 'https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&height=568&format=webp&quality=91&imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-pode-ganhar-novo-nivel-de-dificuldade-revela-dataminer-912x569.jpg', 'Diablo IV para PC, disponivel nas plataformas: Playstation, X-box, PC');

-- INSERT POST FOR TEST
INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title, urlmainimage, description) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<div class="section-text">
<div class="content-image mb-24"><figure style="width: 910px" class="wp-caption alignnone"><img width="910" height="568" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg" class="attachment-910x568 size-910x568" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-327x204.jpg 991w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg"><figcaption class="wp-caption-text">Créditos: Divulgação/Blizzard</figcaption></figure></div>
<p>Na última sexta-feira (16), a Blizzard fez a primeira transmissão de desenvolvedores de <strong>Diablo IV</strong> após o game chegar às lojas. Nela, o diretor Joe Shely afirmou que a empresa já está preparando um <strong>grande patch de atualização que deve trazer diversos buffs</strong> para as classes presentes no game.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-426aebdb-7381-46eb-b5cc-4994b71562d5" style="" data-google-query-id="CIKD2O-5y_8CFdCblQIdfxcDfw"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_0__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_0" name="google_ads_iframe_/21715141650,1071122/desktop_intext_0" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="4"></iframe></div></div></div>
<p>“<em>Nossa filosofia é priorizar a melhoria da escolha observando as coisas que não estão funcionando e as tornando melhores</em>”, <strong>afirmou Shely</strong>. “<em>Agora, não me senti assim nas duas últimas semanas, certo? E quando vim aqui hoje, estava pensando — não tenho uma camisa como essa —, mas eu pensei sobre comprar uma camisa e depois escrever ‘é hora dos buffs’. Eu não fiz isso, mas é hora dos buffs</em>”.</p>
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<lite-youtube videoid="3PO9OY7AIs4" playlabel="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" posterquality="sddefault" params="rel=0" title="Play: Video"></lite-youtube>
</div></figure>
<p>O diretor de Diablo IV não foi específico sobre o que deve mudar no RPG de ação, mas prometeu que <strong>builds que dependem da geração de recursos vão funcionar melho</strong>r. Ele também prometeu que as <a href="https://www.adrenaline.com.br/games/um-unico-chefe-de-diablo-iv-e-responsavel-por-2-de-suas-mortes/">Masmorras de Pesadelo do game</a> vão se tornar mais recompensadoras e trazer mais experiência do que passar pelos labirintos convencionais do jogo.</p>
<h2 id="h-nerfs-sao-necessarios-para-diablo-iv-prosperar">Nerfs são necessários para Diablo IV prosperar</h2>
<p>O gerente-geral da franquia Diablo, Rod Fergusson, também explicou que alguns nerfs que <a href="https://www.adrenaline.com.br/games/diablo-iv-blizzard-nerfou-areas-para-elas-darem-menos-experiencia/">não agradaram aos jogadores</a> são necessários para melhorar o estado geral do game. Segundo ele, as “fazendas de experiência” eliminadas em uma atualização recente <strong>estavam fazendo com que outras partes da aventura acabassem sendo ignoradas</strong>.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-ebedeb73-2363-4dbf-9898-da9b920b111d" style="" data-google-query-id="CNGJ95y_8CFQSGlQIdgeoNAA"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_1__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_1" name="google_ads_iframe_/21715141650,1071122/desktop_intext_1" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="3"></iframe></div></div></div>
<figure class="wp-block-image size-full"><img decoding="async" width="1000" height="563" src="https://uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" class="wp-image-393905" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=640&amp;height=360&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-640x360.jpg 640w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=768&amp;height=432&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-768x432.jpg 768w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=150&amp;height=84&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-150x84.jpg 150w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=1000&amp;height=563&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg 1000w" sizes="(max-width: 1000px) 100vw, 1000px"><figcaption class="wp-element-caption">Foto: Divulgação/Blizzard</figcaption></figure>
<p>Durante a transmissão, os membros da Blizzard também revelaram que as gemas e outros itens que podem ser inseridos em equipamentos <strong>vão deixar de ser colocados no inventário geral dos jogadores</strong>. Segundo Shely, a intenção é que elas passem as ser tratadas com outros materiais que podem ser usados para aprimorar os equipamentos usados.</p>
<p>A companhia também promete fazer diversas mudanças no endgame de Diablo IV, mas reconheceu que <strong>muitos jogadores ainda vão demorar a senti-las</strong>. Segundo a companhia, ainda é uma quantidade relativa pequena de pessoas que terminou a história principal, mas garantir que elas vão ter que o fazer após isso é uma de suas preocupações constantes.</p>
<div class="wp-block-seox-content-feeds">
<article class="feed feed-base feed-conteudo-destacado">
<div class="feed-head">
<small class="feed-head-text">Conteúdo Relacionado </small>
</div>
<div class="feed-bg">
<a href="https://www.adrenaline.com.br/games/campanha-devocao-a-lilith-incentiva-fas-de-diablo-iv-a-doarem-sangue-em-sao-paulo/" title="Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo">
<figure class="feed-image">
<img width="912" height="569" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg" class="attachment-912x569 size-912x569" alt="diablo-iv-doacao-sangue" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-327x204.jpg 992w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg"> <div class="feed-image-hover">
</div>
</figure>
<div class="feed-content">
<div class="line">
<p class="feed-hat hat">Convocação do inferno</p>
</div>
<p class="feed-title">Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo</p>
</div>
</a>
</div>
</article>
</div>
<p>Fonte: <a href="https://www.pcgamer.com/diablo-4-director-it-is-time-for-the-buffs/" target="_blank" rel="noreferrer noopener">PC Gamer</a></p><div style="width: 100%; height: 0; transition: height 1s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: none; line-height: normal; margin: 0 0 2px; padding: 0; color: #aaa; text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-d3807e7e-27b9-4029-a6e7-eefed2d9a517" style="display: block;"></div></div>
</div>', 'Diablo IV promete buffs para personagens, mudanças nas gemas e mais', 'https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&height=568&format=webp&quality=91&imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-pode-ganhar-novo-nivel-de-dificuldade-revela-dataminer-912x569.jpg', 'Diablo IV para PC, disponivel nas plataformas: Playstation, X-box, PC');


INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title, urlmainimage, description) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<div class="section-text">
<div class="content-image mb-24"><figure style="width: 910px" class="wp-caption alignnone"><img width="910" height="568" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/sony-ps5-playstation-5-912x569.jpg" class="attachment-910x568 size-910x568" alt="Sony: Concorra a consoles PS5 e PS VR 2; veja como participar" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/sony-ps5-playstation-5-327x204.jpg 991w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/sony-ps5-playstation-5-912x569.jpg"><figcaption class="wp-caption-text">Créditos: Sony</figcaption></figure></div>
<p>Pronto para concorrer a um <strong>PlayStation 5 e um PS VR2</strong>? A <strong>Sony</strong> está comemorando um ano do lançamento da nova <strong>PlayStation Plus </strong>e iniciou as inscrições para um sorteio especial de aniversário. Os jogadores podem se inscrever até o dia 30 de junho para concorrer ao PS5 e o PS VR2 e todos os usuários com uma conta <strong>PlayStation</strong> podem participar.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-f874dcdd-0861-46cd-8d10-35bed68b58d7" style="" data-google-query-id="CL_5xfmK0_8CFSJK3QId3j0Hiw"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_0__container__" style="border: 0pt none; display: inline-block; width: 100%; height: auto;"><iframe frameborder="0" src="https://c1ae21a73dfc55712ca532f4ee716d24.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html" id="google_ads_iframe_/21715141650,1071122/desktop_intext_0" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="300" height="250" data-is-safeframe="true" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" role="region" aria-label="Advertisement" tabindex="0" data-google-container-id="3" style="border: 0px; vertical-align: bottom; width: 300px; height: 250px;" data-load-complete="true"></iframe></div></div></div>
<p>Para participar os jogadores precisam estar logados com a sua conta no navegador, acessar a <a href="https://www.playstation.com/pt-br/ps-plus/playstation-plus-celebration-competition/" target="_blank" rel="noreferrer noopener">página da promoção</a> e responder corretamente cinco perguntas relacionadas ao universo <strong>PlayStation</strong>. Essas respostas podem ser encontradas em um infográfico presente na própria página de participação. </p>
<h2 class="has-text-align-center"><a href="http://playstation.com/pt-br/ps-plus/playstation-plus-celebration-competition/" target="_blank" rel="noreferrer noopener">CLIQUE AQUI PARA PARTICIPAR DO SORTEIO</a></h2>
<p>As regras de participação estão presentes na página da promoção ou <a href="https://www.playstation.com/pt-br/legal/pspluscelebration/" target="_blank" rel="noreferrer noopener">clicando aqui</a>.</p>
<figure class="wp-block-image size-full"><img decoding="async" width="1200" height="750" src="https://uploads.adrenaline.com.br/2023/05/ps-vr2-sony.jpg" alt="" class="wp-image-384947" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=640&amp;height=400&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-640x400.jpg 640w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=768&amp;height=480&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-768x480.jpg 768w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=210&amp;height=131&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-210x131.jpg 210w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-327x204.jpg 327w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=444&amp;height=277&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-444x277.jpg 444w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=678&amp;height=423&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-678x423.jpg 678w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=292&amp;height=182&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-292x182.jpg 292w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-912x569.jpg 912w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=1029&amp;height=642&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-1029x642.jpg 1029w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=150&amp;height=94&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony-150x94.jpg 150w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=1200&amp;height=750&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/05/ps-vr2-sony.jpg 1200w" sizes="(max-width: 1200px) 100vw, 1200px"><figcaption class="wp-element-caption">Foto: Triyansh Gill/Unsplash</figcaption></figure>
<p>Outra ação da Sony neste período de comemoração são os cinco avatares exclusivos que podem ser resgatados gratuitamente na conta do usuário, <a href="https://www.adrenaline.com.br/games/playstation/ps-plus-novos-avatares-ja-estao-disponiveis-para-resgate-gratuito/" target="_blank" rel="noreferrer noopener">confira aqui os detalhes desta oferta</a>.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-3b4a613b-035c-48cc-a210-24ce88204afe" style="" data-google-query-id="CP7HpfmK0_8CFc1B3QIdrxgNGA"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_1__container__" style="border: 0pt none; display: inline-block; width: 100%; height: auto;"><iframe frameborder="0" src="https://c1ae21a73dfc55712ca532f4ee716d24.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html" id="google_ads_iframe_/21715141650,1071122/desktop_intext_1" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="300" height="250" data-is-safeframe="true" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" role="region" aria-label="Advertisement" tabindex="0" data-google-container-id="2" style="border: 0px; vertical-align: bottom; width: 300px; height: 250px;" data-load-complete="true"></iframe></div></div></div>
<hr class="wp-block-separator has-alpha-channel-opacity">
<h2 class="has-text-align-center" id="h-beneficios-da-nova-ps-plus">BENEFÍCIOS DA NOVA PS PLUS</h2>
<hr class="wp-block-separator has-alpha-channel-opacity">
<p>A Nova PS Plus foi lançada ano passado e trouxe a separação da assinatura em três níveis: <strong>Essential, Extra e Deluxe</strong>, com cada um deles ofertando diferentes benefícios que incluem catálogo de jogos e testes para jogos selecionados.</p>
<p>Enquanto o plano PS Plus Essential segue o modelo da PS Plus anterior com novos jogos sendo disponibilizados para a conta do assinante todos os meses, os usuários que optam pelos planos mais caros da PS Plus possuem acesso a uma biblioteca de jogos selecionados com grandes títulos incluídos. </p>
<figure class="wp-block-image size-full"><img decoding="async" width="1200" height="545" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?format=webp&amp;quality=91&amp;imagick=/wp-content/uploads/2023/03/oferta-ps-plus.jpg" alt="" class="wp-image-183294"></figure>
<p>Além disso, os assinantes da PS Plus Deluxe contam também com acesso a jogos clássicos e período de testes em jogos como&nbsp;<strong>God of War Ragnarok,&nbsp;</strong>que possui três horas disponíveis para teste, além de outros jogos selecionados.</p><div style="width: 100%; height: 0; transition: height 1s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: none; line-height: normal; margin: 0 0 2px; padding: 0; color: #aaa; text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-db9f2613-f236-4cff-9211-5dd557316da0" style="display: block;"></div></div>
<p>O catálogo da PS Plus Extra e Deluxe atualmente conta com diversos títulos da própria Sony e desenvolvidos por outras empresas. Alguns dos jogos que entraram no catálogo recentemente são<strong>&nbsp;Horizon: Forbidden West, Ratchet &amp; Clank: Em Uma Nova Dimensão, Kena: Bridge of Spirits, Ghostwire: Tokyo, Death Stranding: Director’s Cut e Uncharted: Coleção Legado dos Ladrões</strong>.</p>
<p class="has-text-align-center">…</p>
<p>O que você achou dos avatares exclusivos desta celebração de 1 ano da nova PS Plus? Você aprovou este novo modelo de assinatura adotado pela Sony? Participe nos comentários com a sua opinião!</p>
<p class="has-text-align-right"><a href="https://www.adrenaline.com.br/noticias/conheca-os-novos-processadores-intel-core-ultra/">FIM DE UMA ERA: Conheça os novos processadores Intel Core Ultra</a></p>
<div class="wp-block-seox-content-feeds">
<article class="feed feed-base feed-conteudo-destacado">
<div class="feed-head">
<small class="feed-head-text">Conteúdo Relacionado </small>
</div>
<div class="feed-bg">
<a href="https://www.adrenaline.com.br/games/lancamentos-de-19-06-a-23-06-em-jogos-para-pc-playstation-xbox-e-switch/" title="Lançamentos de 19/06 a 23/06 em jogos para PC, PlayStation, Xbox e Switch">
<figure class="feed-image">
<img width="912" height="569" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/FINAL-FANTASY-XVI-912x569.jpg" class="attachment-912x569 size-912x569" alt="Final Fantasy XVI" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/FINAL-FANTASY-XVI-327x204.jpg 992w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/FINAL-FANTASY-XVI-912x569.jpg"> <div class="feed-image-hover">
</div>
</figure>
<div class="feed-content">
<div class="line">
<p class="feed-hat hat">Final Fantasy XVI e mais</p>
</div>
<p class="feed-title">Lançamentos de 19/06 a 23/06 em jogos para PC, PlayStation, Xbox e Switch</p>
</div>
</a>
</div>
</article>
</div>
<p>Via: <a href="https://www.playstation.com/pt-br/ps-plus/whats-new/?sf267457953=1#avatars" target="_blank" rel="noreferrer noopener">PlayStation</a></p>
</div>', 'Sony: Concorra a consoles PS5 e PS VR 2; veja como participar', 'https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&height=568&format=webp&quality=91&imagick=uploads.adrenaline.com.br/2023/05/sony-ps5-playstation-5-912x569.jpg', 'Participe aqui da promoção.');


INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title, urlmainimage, description) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<div></div>', 'Nintendo Direct: Super Mario Bros. Wonder chega em Outubro no Nintendo Switch', 'https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&height=568&format=webp&quality=91&imagick=uploads.adrenaline.com.br/2023/06/super-mario-bros-wonder-chamada-912x569.jpg', 'Super Mario Bros Wonder, lança dia 20 de Outubro.');

INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title, urlmainimage, description) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<div></div>', 'Levantamento do site WCCFtech aponta para uma certa exclusividade da tecnologia da AMD', 'https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&height=568&format=webp&quality=91&imagick=uploads.adrenaline.com.br/2023/06/amd-fsr-912x569.jpg', 'Jogos com selo AMD FSR não costumam.');

INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title, urlmainimage, description) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<div></div>', 'Kraven, O Caçador: Filme ganha primeiro trailer BRUTAL, com muita ação!', 'https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&height=568&format=webp&quality=91&imagick=uploads.adrenaline.com.br/2023/05/marvels-spider-man-2-912x569.jpg', 'Filme será 18+ e terá lancamento em 5 de outubro nos cinemas.');



-- INSERT POST FOR TEST
INSERT INTO public.post_badges (badge_id, post_id) VALUES(1, 1);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(51, 1);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(101, 1);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(151, 1);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(201, 1);


INSERT INTO public.post_badges (badge_id, post_id) VALUES(51, 51);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(251, 51);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(101, 51);

INSERT INTO public.post_badges (badge_id, post_id) VALUES(51, 101);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(101, 101);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(201, 101);

INSERT INTO public.post_badges (badge_id, post_id) VALUES(51, 151);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(201, 151);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(401, 151);


INSERT INTO public.post_badges (badge_id, post_id) VALUES(51, 201);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(251, 201);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(301, 201);
INSERT INTO public.post_badges (badge_id, post_id) VALUES(351, 201);


INSERT INTO public.post_badges (badge_id, post_id) VALUES(101, 251);




INSERT INTO public.post_badges (badge_id, post_id) VALUES(301, 301);

INSERT INTO public.post_badges (badge_id, post_id) VALUES(351, 351);