INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<h1>Loren Ipsum</h1>', 'TITULO');

INSERT INTO public.post (highlighted, datepost, id, user_id, posttext, posttexthtml, title) VALUES (true, current_timestamp, nextval('post_seq'), 1, 'Loren Ipsum', '<div class="section-text">
<div class="content-image mb-24"><figure style="width: 910px" class="wp-caption alignnone"><img width="910" height="568" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg" class="attachment-910x568 size-910x568" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-327x204.jpg 991w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=910&amp;height=568&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-912x569.jpg"><figcaption class="wp-caption-text">Créditos: Divulgação/Blizzard</figcaption></figure></div>
<p>Na última sexta-feira (16), a Blizzard fez a primeira transmissão de desenvolvedores de <strong>Diablo IV</strong> após o game chegar às lojas. Nela, o diretor Joe Shely afirmou que a empresa já está preparando um <strong>grande patch de atualização que deve trazer diversos buffs</strong> para as classes presentes no game.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-426aebdb-7381-46eb-b5cc-4994b71562d5" style="" data-google-query-id="CIKD2O-5y_8CFdCblQIdfxcDfw"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_0__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_0" name="google_ads_iframe_/21715141650,1071122/desktop_intext_0" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="4"></iframe></div></div></div>
<p>“<em>Nossa filosofia é priorizar a melhoria da escolha observando as coisas que não estão funcionando e as tornando melhores</em>”, <strong>afirmou Shely</strong>. “<em>Agora, não me senti assim nas duas últimas semanas, certo? E quando vim aqui hoje, estava pensando — não tenho uma camisa como essa —, mas eu pensei sobre comprar uma camisa e depois escrever ‘é hora dos buffs’. Eu não fiz isso, mas é hora dos buffs</em>”.</p>
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<lite-youtube videoid="3PO9OY7AIs4" playlabel="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" posterquality="sddefault" params="rel=0" title="Play: Video"></lite-youtube>
</div></figure>
<p>O diretor de Diablo IV não foi específico sobre o que deve mudar no RPG de ação, mas prometeu que <strong>builds que dependem da geração de recursos vão funcionar melho</strong>r. Ele também prometeu que as <a href="https://www.adrenaline.com.br/games/um-unico-chefe-de-diablo-iv-e-responsavel-por-2-de-suas-mortes/">Masmorras de Pesadelo do game</a> vão se tornar mais recompensadoras e trazer mais experiência do que passar pelos labirintos convencionais do jogo.</p>
<h2 id="h-nerfs-sao-necessarios-para-diablo-iv-prosperar">Nerfs são necessários para Diablo IV prosperar</h2>
<p>O gerente-geral da franquia Diablo, Rod Fergusson, também explicou que alguns nerfs que <a href="https://www.adrenaline.com.br/games/diablo-iv-blizzard-nerfou-areas-para-elas-darem-menos-experiencia/">não agradaram aos jogadores</a> são necessários para melhorar o estado geral do game. Segundo ele, as “fazendas de experiência” eliminadas em uma atualização recente <strong>estavam fazendo com que outras partes da aventura acabassem sendo ignoradas</strong>.</p><div style="width: 100%; height: auto; transition: height 1s ease 0s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: block; line-height: normal; margin: 0px 0px 2px; padding: 0px; color: rgb(170, 170, 170); text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-ebedeb73-2363-4dbf-9898-da9b920b111d" style="" data-google-query-id="CNGJ9--5y_8CFQSGlQIdgeoNAA"><div id="google_ads_iframe_/21715141650,1071122/desktop_intext_1__container__" style="border: 0pt none; width: 100%; height: auto;"><iframe id="google_ads_iframe_/21715141650,1071122/desktop_intext_1" name="google_ads_iframe_/21715141650,1071122/desktop_intext_1" title="3rd party ad content" width="336" height="280" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" style="border: 0px; vertical-align: bottom; width: 336px; height: 280px;" data-load-complete="true" data-google-container-id="3"></iframe></div></div></div>
<figure class="wp-block-image size-full"><img decoding="async" width="1000" height="563" src="https://uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg" alt="Diablo IV promete buffs para personagens, mudanças nas gemas e mais" class="wp-image-393905" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=640&amp;height=360&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-640x360.jpg 640w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=768&amp;height=432&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-768x432.jpg 768w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=150&amp;height=84&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02-150x84.jpg 150w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=1000&amp;height=563&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-promete-buffs-para-personagens-mudancas-nas-gemas-e-mais-02.jpg 1000w" sizes="(max-width: 1000px) 100vw, 1000px"><figcaption class="wp-element-caption">Foto: Divulgação/Blizzard</figcaption></figure>
<p>Durante a transmissão, os membros da Blizzard também revelaram que as gemas e outros itens que podem ser inseridos em equipamentos <strong>vão deixar de ser colocados no inventário geral dos jogadores</strong>. Segundo Shely, a intenção é que elas passem as ser tratadas com outros materiais que podem ser usados para aprimorar os equipamentos usados.</p>
<p>A companhia também promete fazer diversas mudanças no endgame de Diablo IV, mas reconheceu que <strong>muitos jogadores ainda vão demorar a senti-las</strong>. Segundo a companhia, ainda é uma quantidade relativa pequena de pessoas que terminou a história principal, mas garantir que elas vão ter que o fazer após isso é uma de suas preocupações constantes.</p>
<div class="wp-block-seox-content-feeds">
<article class="feed feed-base feed-conteudo-destacado">
<div class="feed-head">
<small class="feed-head-text">Conteúdo Relacionado </small>
</div>
<div class="feed-bg">
<a href="https://www.adrenaline.com.br/games/campanha-devocao-a-lilith-incentiva-fas-de-diablo-iv-a-doarem-sangue-em-sao-paulo/" title="Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo">
<figure class="feed-image">
<img width="912" height="569" src="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg" class="attachment-912x569 size-912x569" alt="diablo-iv-doacao-sangue" decoding="async" srcset="https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=327&amp;height=204&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-327x204.jpg 992w, https://www.adrenaline.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=912&amp;height=569&amp;format=webp&amp;quality=91&amp;imagick=uploads.adrenaline.com.br/2023/06/Diablo-IV-desenvolvedores-falam-sobre-suas-expectativas-para-o-jogo-912x569.jpg"> <div class="feed-image-hover">
</div>
</figure>
<div class="feed-content">
<div class="line">
<p class="feed-hat hat">Convocação do inferno</p>
</div>
<p class="feed-title">Campanha “Devoção à Lilith” incentiva fãs de Diablo IV a doarem sangue em São Paulo</p>
</div>
</a>
</div>
</article>
</div>
<p>Fonte: <a href="https://www.pcgamer.com/diablo-4-director-it-is-time-for-the-buffs/" target="_blank" rel="noreferrer noopener">PC Gamer</a></p><div style="width: 100%; height: 0; transition: height 1s; text-align: center; margin: auto; padding: 20px 0px; display: inline-block;"><p class="denakop-pub-text" style="display: none; line-height: normal; margin: 0 0 2px; padding: 0; color: #aaa; text-align: center; font-size: 10px; font-family: Arial, Helvetica, sans-serif;">PUBLICIDADE</p><div id="denakop-auto-intext-d3807e7e-27b9-4029-a6e7-eefed2d9a517" style="display: block;"></div></div>

</div>', 'Diablo IV promete buffs para personagens, mudanças nas gemas e mais');